### PR TITLE
A quick guide on how to report error for our coleauges

### PR DESCRIPTION
**Pull request by zinob**
This is mostly meant for team-leaders and other non-devs as a guide on how to get faster and less sassy help from the dev-team

### CODE REVIEW

**Comment by mantono** [comment]
Made a pull request on your pull request/fork.

**Comment by williamhogman** [comment]
Add link in TOC in README.md

**Comment by williamhogman** [comment]
also run Ispell 😏

**Comment by mantono** [comment]
I still have some (minor) concerns that were addressed in my PR to to PR.

**Pull request merged**
